lep-as:
  image: mrsvan/docker-liferay-mysql:7.0.0
  container_name: lep-as
  dns:
  - 8.8.8.8
  - 8.8.4.4
  ports:
  - "443:8443"
  links:
  - "lep-db"
lep-db:
  image: mysql:5.7
  container_name: lep-db
  dns:
  - 8.8.8.8
  - 8.8.4.4
  ports:
  - "3306:3306"
  environment:
  - MYSQL_ROOT_PASSWORD=adminpwd
  - MYSQL_USER=lportal
  - MYSQL_PASSWORD=lportal
  - MYSQL_DATABASE=lportal
